# Generated by Django 4.2.1 on 2023-06-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage_ticket',
            old_name='assignee_id',
            new_name='assignee',
        ),
    ]
